// <auto-generated />

using System;
using FishingJournal.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

namespace FishingJournal.Migrations
{
    [DbContext(typeof(DefaultContext))]
    partial class DefaultContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FishingJournal.Models.JournalEntry", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy",
                        SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<DateTime>("Date")
                    .HasColumnType("datetime2");

                b.Property<string>("Latitude")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("LocationOverride")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Longitude")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Notes")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("WeatherSummary")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.ToTable("JournalEntries");
            });
#pragma warning restore 612, 618
        }
    }
}